import { Layout } from "@/components/layout/Layout";
import { SEO } from "@/components/SEO";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Helmet } from "react-helmet-async";
import { Globe, Lock, Shield, Database, CheckCircle, ArrowRight } from "lucide-react";

const DataSovereignty = () => {
  return (
    <Layout>
      <SEO
        title="Why Data Sovereignty Matters in Africa's Lithium Supply Chain"
        description="An in-depth explainer on data sovereignty in Africa's lithium supply chain: why it matters for regulators, miners, and buyers, and how Beldium's infrastructure enables it."
        canonical="/resources/data-sovereignty"
        keywords="data sovereignty Africa, lithium supply chain Africa, mineral data ownership, African lithium data, data governance mining, resource data sovereignty, critical minerals traceability, Nigeria lithium data"
      />
      <Helmet>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": "Why Data Sovereignty Matters in Africa's Lithium Supply Chain",
            "description": "An explainer on why African nations must own, control, and govern the data generated by their lithium supply chain, and how Beldium's architecture supports it.",
            "url": "https://beldium.com/resources/data-sovereignty",
            "publisher": { "@type": "Organization", "name": "Beldium Inc", "url": "https://beldium.com" },
            "author": { "@type": "Person", "name": "David Obi", "jobTitle": "Founder" },
            "datePublished": "2025-06-01",
            "dateModified": "2026-07-04",
            "about": [
              { "@type": "Thing", "name": "Data Sovereignty" },
              { "@type": "Thing", "name": "African Lithium Supply Chain" },
              { "@type": "Thing", "name": "Critical Minerals Traceability" },
            ],
          })}
        </script>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
              {
                "@type": "Question",
                "name": "What is data sovereignty in the context of mining?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "Data sovereignty in mining is the principle that the data generated by extracting, trading, and moving minerals, production volumes, assay results, chain-of-custody records, export documentation, is governed by the laws and institutions of the country where those minerals originate.",
                },
              },
              {
                "@type": "Question",
                "name": "Why does data sovereignty matter for Africa's lithium supply chain?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "Lithium is a strategic mineral for the global energy transition. Without sovereign control of production, trade, and compliance data, African governments cannot set fair royalties, enforce environmental standards, or negotiate value-added processing agreements with international buyers.",
                },
              },
              {
                "@type": "Question",
                "name": "How does Beldium support data sovereignty?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "Beldium's platform stores mineral data within African jurisdictions, gives miners ownership of their production records, provides regulators with aggregate industry intelligence, and publishes transparent, auditable data governance policies.",
                },
              },
            ],
          })}
        </script>
      </Helmet>

      <section className="section-padding bg-gradient-to-b from-primary/5 to-background">
        <div className="container-wide">
          <div className="max-w-3xl mx-auto text-center">
            <Link to="/resources" className="inline-flex items-center text-sm text-primary hover:underline mb-4">← Back to Resources</Link>
            <span className="block mb-4">
              <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-sm font-medium text-primary">
                Explainer · Policy & Governance
              </span>
            </span>
            <h1 className="text-4xl sm:text-5xl font-bold text-foreground mb-6">
              Why Data Sovereignty Matters in Africa's Lithium Supply Chain
            </h1>
            <p className="text-xl text-muted-foreground">
              Africa mines the lithium that powers the global energy transition, but the data those minerals
              generate, production volumes, assay results, chain-of-custody records, pricing intelligence , 
              still flows off the continent with no institutional oversight. This explainer sets out why that
              matters, what it costs, and how it can be fixed.
            </p>
          </div>
        </div>
      </section>

      <section className="section-padding bg-background">
        <div className="container-wide max-w-3xl mx-auto prose-container">
          <h2 className="text-2xl font-bold text-foreground mb-4">What data sovereignty actually means</h2>
          <p className="text-muted-foreground mb-4">
            Data sovereignty is the principle that data is governed by the laws and institutions of the
            jurisdiction where it originates. Applied to Africa's lithium supply chain, it means that the
            records generated when spodumene leaves a pit in Nasarawa, when a lot is graded at an aggregation
            point in Kaduna, or when a container clears the Port of Lagos, are subject to Nigerian law and
            accessible to Nigerian regulators, not stored exclusively in a foreign trader's private database.
          </p>
          <p className="text-muted-foreground mb-6">
            It is not a technical curiosity. It is the difference between a country that can price, tax, and
            plan around its own mineral economy, and one that has to buy back intelligence about its own
            resources from third-party consultancies.
          </p>

          <h2 className="text-2xl font-bold text-foreground mb-4">The data extraction problem</h2>
          <p className="text-muted-foreground mb-4">
            When international companies extract minerals from African soil, they extract data too:
            geological surveys, drill results, production volumes, quality assessments, trade flows, and
            realised pricing. In most jurisdictions across the continent, that data becomes the proprietary
            asset of the foreign entity that captured it. It leaves in spreadsheets, ERPs, and satellite
            feeds long before the ore does.
          </p>
          <p className="text-muted-foreground mb-6">
            The consequence is asymmetric. Buyers in Shanghai and Rotterdam have a more accurate picture of
            what a mine in Kogi produced last quarter than the ministry that licensed it. Traders can model
            African supply curves that governments themselves cannot see. Royalty regimes are negotiated
            against price benchmarks set thousands of kilometres away. In every one of these exchanges, the
            country of origin is the least-informed party at the table.
          </p>

          <h2 className="text-2xl font-bold text-foreground mb-4">Why this matters for lithium specifically</h2>
          <p className="text-muted-foreground mb-4">
            Lithium is not just another commodity. It is the anchor mineral for battery manufacturing,
            electric vehicles, and grid-scale energy storage, which means demand is structural rather than
            cyclical. Every industrial policy in Europe, North America, and East Asia now treats lithium
            supply as a national-security question. Africa, with confirmed reserves across Nigeria, the DRC,
            Zimbabwe, Ghana, Mali, and Namibia, sits at the centre of that map.
          </p>
          <p className="text-muted-foreground mb-6">
            Countries that cannot see their own lithium flows in real time cannot participate in that
            geopolitical conversation on equal footing. They cannot credibly commit to offtake volumes,
            enforce local processing mandates, or attract the refining and cell-manufacturing investment
            that turns a resource into an industry. Data sovereignty is the precondition for value addition.
          </p>

          <h2 className="text-2xl font-bold text-foreground mb-4">The four things sovereign data enables</h2>
          <div className="space-y-4 mb-8">
            {[
              { icon: Globe, title: "National resource intelligence", text: "Governments need accurate, near-real-time data on production, grade, and export to set royalty rates, forecast revenue, and plan infrastructure. Without it, budgets are guesswork and every policy conversation defaults to the numbers foreign buyers choose to share." },
              { icon: Shield, title: "Regulatory enforcement", text: "Regulators cannot police what they cannot see. Sovereign data on licensed sites, permitted volumes, and chain of custody is what separates enforceable rules from paper ones, and what makes illegal mining, under-declaration, and environmental breaches actually detectable." },
              { icon: Lock, title: "Economic sovereignty at the negotiating table", text: "Production, quality, and pricing data is economic intelligence. Countries that own it can negotiate offtake terms, local-content requirements, and downstream investment on their own numbers. Countries that don't, negotiate on someone else's." },
              { icon: Database, title: "Institutional capacity over time", text: "Every mature mining jurisdiction, Australia, Chile, Canada, was built on decades of accumulated public geological and production data. African nations lose that compounding advantage every time a dataset leaves the continent without a domestic copy." },
            ].map((item) => (
              <div key={item.title} className="card-elevated p-6 flex gap-4">
                <item.icon className="h-6 w-6 text-primary flex-shrink-0 mt-1" />
                <div>
                  <h3 className="font-semibold text-foreground mb-1">{item.title}</h3>
                  <p className="text-muted-foreground text-sm">{item.text}</p>
                </div>
              </div>
            ))}
          </div>

          <h2 className="text-2xl font-bold text-foreground mb-4">Where sovereignty breaks down today</h2>
          <p className="text-muted-foreground mb-4">
            In practice, the lithium supply chain in most African producing countries fragments across
            informal miners, aggregators, licensed exporters, freight forwarders, port authorities, and
            offshore buyers. Each link keeps its own records, in its own format, on its own systems. The
            ministry of mines might have a licence register. Customs might have an export line. The buyer
            has an ERP entry. None of them reconcile.
          </p>
          <p className="text-muted-foreground mb-6">
            The gap between those records is where illegal export, mis-invoicing, royalty leakage, and
            traceability disputes live. It is also where the credibility of African supply, the thing
            international battery makers need before they commit to long-term offtake, quietly collapses.
            Fixing sovereignty is therefore not a defensive move. It is what makes the continent bankable.
          </p>

          <h2 className="text-2xl font-bold text-foreground mb-4">Traceability, ESG, and the buyer's incentive</h2>
          <p className="text-muted-foreground mb-6">
            Global battery buyers now operate under regulations, the EU Battery Regulation, the US Inflation
            Reduction Act's sourcing rules, OECD due-diligence guidance, that require verifiable
            chain-of-custody data. Buyers cannot meet those obligations from opaque supply chains, which is
            why they increasingly pay a premium for verified African material. A country with sovereign,
            queryable production and compliance data can supply that verification directly, rather than
            ceding the audit function (and the margin) to third-party assurance firms abroad.
          </p>

          <h2 className="text-2xl font-bold text-foreground mb-4">Beldium's approach to data sovereignty</h2>
          <p className="text-muted-foreground mb-4">
            Beldium's data architecture is built on the principle that mineral data belongs to the
            stakeholders who generate it, and is governed by the jurisdiction where it originates. In
            practice that means:
          </p>
          <ul className="space-y-3 mb-8">
            {[
              "Miners retain ownership of their production records, with granular control over which buyers, regulators, or financiers can see what.",
              "Regulators receive aggregate industry intelligence, production, exports, royalties, compliance status, without compromising individual operator confidentiality.",
              "Data residency defaults to African jurisdictions, so records generated in Nigeria are governed by Nigerian law.",
              "Chain-of-custody records are cryptographically linked from pit to port, giving buyers verifiable traceability without exposing counterparties' commercial data.",
              "Governance policies are published, auditable, and versioned. No third-party monetisation of participant data occurs without explicit, revocable consent.",
            ].map((point) => (
              <li key={point} className="flex items-start gap-3">
                <CheckCircle className="h-5 w-5 text-accent flex-shrink-0 mt-0.5" />
                <span className="text-foreground">{point}</span>
              </li>
            ))}
          </ul>

          <h2 className="text-2xl font-bold text-foreground mb-4">What good policy looks like</h2>
          <p className="text-muted-foreground mb-4">
            Sovereign data infrastructure is not built by platforms alone. It is built by policy that
            requires it. The countries that will lead Africa's lithium era are the ones that mandate
            digital reporting of production and export volumes, require in-country hosting of primary
            mining data, publish national mineral data standards, and make regulator access to
            operator-level records a licensing condition rather than an afterthought.
          </p>
          <p className="text-muted-foreground mb-6">
            None of this is hostile to investors. The opposite: institutional buyers, development finance
            institutions, and battery manufacturers are already asking for exactly this kind of verifiable
            data. Countries that provide it will attract capital. Countries that don't will remain price
            takers.
          </p>

          <h2 className="text-2xl font-bold text-foreground mb-4">A call to action</h2>
          <p className="text-muted-foreground mb-8">
            Data sovereignty is not a technical feature. It is a political and economic imperative. As
            Africa's lithium economy scales from artisanal pits to industrial supply, the continent has a
            narrow window to build the institutional data infrastructure that will define how much of the
            value stays home. Beldium is building that infrastructure, pit to port, in-country, and
            accountable to the regulators who need it.
          </p>
        </div>
      </section>

      <section className="section-padding bg-secondary/50 text-center">
        <div className="container-wide max-w-2xl mx-auto">
          <h2 className="text-3xl font-bold text-foreground mb-4">Continue reading</h2>
          <div className="flex flex-wrap justify-center gap-4">
            <Button variant="outline" asChild><Link to="/resources/lithium-in-nigeria">Lithium in Nigeria</Link></Button>
            <Button variant="outline" asChild><Link to="/resources/lithium-supply-chain">Lithium Supply Chain</Link></Button>
            <Button variant="outline" asChild><Link to="/resources/infrastructure-gaps">Infrastructure Gaps</Link></Button>
            <Button variant="outline" asChild><Link to="/governance">Governance Framework</Link></Button>
            <Button variant="outline" asChild><Link to="/data-architecture">Data Architecture</Link></Button>
            <Button asChild><Link to="/contact">Discuss with Our Team <ArrowRight className="ml-2 h-5 w-5" /></Link></Button>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default DataSovereignty;
