import { Layout } from "@/components/layout/Layout";
import { SEO } from "@/components/SEO";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Helmet } from "react-helmet-async";
import { BarChart3, Database, Globe, Shield, Truck, Users, CheckCircle, ArrowRight } from "lucide-react";

const gaps = [
  {
    icon: Database,
    title: "Data Infrastructure",
    description: "Most African mining operations lack structured data collection systems. Production volumes, quality grades, and pricing data are recorded informally or not at all.",
    impact: "Without structured data, institutional investors cannot assess market opportunity, and governments cannot accurately forecast revenue or enforce compliance.",
    beldiumResponse: "GPS-tagged, timestamped production data capture at mine sites with standardized quality grading and automated reporting.",
  },
  {
    icon: Shield,
    title: "Compliance Infrastructure",
    description: "Regulatory compliance in Africa's mineral sector is largely manual, paper-based, and fragmented across jurisdictions, creating gaps that enable illegal mining and trade.",
    impact: "International buyers face due diligence risk, and legitimate miners are disadvantaged by competitors who bypass compliance requirements.",
    beldiumResponse: "Digitized compliance verification covering KYC, licensing, environmental standards, and export documentation with automated monitoring.",
  },
  {
    icon: Truck,
    title: "Logistics Infrastructure",
    description: "The gap between mine site and export terminal is where most value leakage occurs. Informal logistics networks lack documentation, insurance, and accountability.",
    impact: "Quality degradation, theft, documentation gaps, and delays reduce the value African miners receive and increase risk for buyers.",
    beldiumResponse: "Structured logistics coordination with full documentation, GPS tracking, and customs clearance support from mine to port.",
  },
  {
    icon: Globe,
    title: "Market Access Infrastructure",
    description: "Artisanal and small-scale miners are disconnected from formal markets. Exploitative intermediaries capture most of the value generated by mineral production.",
    impact: "Miners receive a fraction of fair market value. Buyers cannot access verified supply. The formal economy loses revenue to informal channels.",
    beldiumResponse: "Verified marketplace connecting KYC-confirmed miners with legitimate buyers through transparent, structured trade infrastructure.",
  },
];

const InfrastructureGaps = () => {
  return (
    <Layout>
      <SEO
        title="Infrastructure Gaps in African Mineral Intelligence"
        description="Mapping the critical gaps in data, compliance, logistics, and market access infrastructure preventing Africa's mineral sector from reaching institutional standards."
        canonical="/resources/infrastructure-gaps"
        keywords="African mining infrastructure, mineral intelligence gaps, mining data gaps Africa, lithium infrastructure Africa, mining technology gaps"
      />
      <Helmet>
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": "Infrastructure Gaps in African Mineral Intelligence",
            "description": "Mapping critical gaps in data, compliance, and logistics infrastructure in Africa's mineral sector.",
            "url": "https://beldium.com/resources/infrastructure-gaps",
            "publisher": { "@type": "Organization", "name": "Beldium Inc", "url": "https://beldium.com" },
            "author": { "@type": "Person", "name": "David Obi", "jobTitle": "Founder" },
            "datePublished": "2025-06-01",
            "dateModified": "2026-04-08",
          })}
        </script>
      </Helmet>

      <section className="section-padding bg-gradient-to-b from-primary/5 to-background">
        <div className="container-wide">
          <div className="max-w-3xl mx-auto text-center">
            <Link to="/resources" className="inline-flex items-center text-sm text-primary hover:underline mb-4">← Back to Resources</Link>
            <span className="block mb-4">
              <span className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-sm font-medium text-primary">
                Infrastructure Analysis
              </span>
            </span>
            <h1 className="text-4xl sm:text-5xl font-bold text-foreground mb-6">
              Infrastructure Gaps in African Mineral Intelligence
            </h1>
            <p className="text-xl text-muted-foreground">
              Africa's solid minerals sector is valued at over $3 trillion, yet critical infrastructure gaps 
              in data, compliance, and logistics prevent the sector from reaching institutional-grade standards.
            </p>
          </div>
        </div>
      </section>

      <section className="section-padding bg-background">
        <div className="container-wide space-y-10">
          {gaps.map((gap) => (
            <div key={gap.title} className="card-elevated p-8 md:p-10">
              <div className="flex items-start gap-6">
                <div className="h-14 w-14 rounded-xl bg-primary/10 flex items-center justify-center flex-shrink-0">
                  <gap.icon className="h-7 w-7 text-primary" />
                </div>
                <div className="flex-1">
                  <h2 className="text-2xl font-bold text-foreground mb-3">{gap.title}</h2>
                  <p className="text-muted-foreground mb-4">{gap.description}</p>
                  
                  <div className="bg-destructive/5 border border-destructive/20 rounded-lg p-4 mb-4">
                    <p className="text-sm"><span className="font-semibold text-destructive">Impact:</span> <span className="text-foreground">{gap.impact}</span></p>
                  </div>
                  
                  <div className="bg-accent/10 border border-accent/20 rounded-lg p-4">
                    <p className="text-sm"><span className="font-semibold text-accent">Beldium's Response:</span> <span className="text-foreground">{gap.beldiumResponse}</span></p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      <section className="section-padding bg-secondary/50">
        <div className="container-wide max-w-3xl mx-auto text-center">
          <h2 className="text-3xl font-bold text-foreground mb-4">Closing the Gap Together</h2>
          <p className="text-muted-foreground mb-8">
            Addressing Africa's mineral infrastructure gaps requires collaboration between governments, 
            industry, technology providers, and international institutions. Beldium is building the 
            infrastructure layer, but the ecosystem requires collective participation.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Button asChild><Link to="/partnerships">Explore Partnership Pathways <ArrowRight className="ml-2 h-5 w-5" /></Link></Button>
            <Button variant="outline" asChild><Link to="/resources/data-sovereignty">Data Sovereignty</Link></Button>
            <Button variant="outline" asChild><Link to="/governance">Governance Framework</Link></Button>
          </div>
        </div>
      </section>
    </Layout>
  );
};

export default InfrastructureGaps;
